// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WEB_API_KEY'),
    appId: '1:651326960663:web:1ba717e02cf22a48695852',
    messagingSenderId: '651326960663',
    projectId: 'seedvest-d230a',
    authDomain: 'seedvest-d230a.firebaseapp.com',
    storageBucket: 'seedvest-d230a.firebasestorage.app',
    measurementId: 'G-M6JC88B6H5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_ANDROID_API_KEY'),
    appId: '1:651326960663:android:0a95b6e8e9e343a8695852',
    messagingSenderId: '651326960663',
    projectId: 'seedvest-d230a',
    storageBucket: 'seedvest-d230a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY'),
    appId: '1:651326960663:ios:10bd093b035da6a4695852',
    messagingSenderId: '651326960663',
    projectId: 'seedvest-d230a',
    storageBucket: 'seedvest-d230a.firebasestorage.app',
    iosBundleId: 'com.example.seedvestMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_MACOS_API_KEY'),
    appId: '1:651326960663:ios:10bd093b035da6a4695852',
    messagingSenderId: '651326960663',
    projectId: 'seedvest-d230a',
    storageBucket: 'seedvest-d230a.firebasestorage.app',
    iosBundleId: 'com.example.seedvestMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WINDOWS_API_KEY'),
    appId: '1:651326960663:web:954e8d5cdbe1c1da695852',
    messagingSenderId: '651326960663',
    projectId: 'seedvest-d230a',
    authDomain: 'seedvest-d230a.firebaseapp.com',
    storageBucket: 'seedvest-d230a.firebasestorage.app',
    measurementId: 'G-1JPYPGWQN8',
  );
}
